---
- name: install nginx
  apt:
    name: nginx
    state: latest

- name: install php7.1 with modules, git and composer
  apt: name={{ item }} update_cache=yes state=present
  with_items:
    - git
    - curl
    - php7.1
    - php7.1-cli
    - php7.1-curl
    - php7.1-fpm
    - php7.1-intl
    - php7.1-json
    - php7.1-mcrypt
    - php7.1-mysql
    - php7.1-gd
    - php7.1-mbstring
    - php7.1-opcache
    - php7.1-readline
    - php7.1-xml
    - php7.1-zip
    - php-xdebug
    - composer

- name: start services
  service: name=nginx state=started enabled=yes
