---
- name: install nginx
  apt:
    name: nginx
    state: latest

- name: install php7.2 with modules and curl
  apt: name={{ item }} update_cache=yes state=present
  with_items:
    - curl
    - php7.2
    - php7.2-cli
    - php7.2-curl
    - php7.2-fpm
    - php7.2-intl
    - php7.2-gettext
    - php7.2-json
    - php7.2-mysql
    - php7.2-gd
    - php7.2-mbstring
    - php7.2-opcache
    - php7.2-readline
    - php7.2-xml
    - php7.2-zip

- name: start nginx service
  service: name=nginx state=started enabled=yes
