---
icinga2_key: "https://packages.icinga.com/icinga.key"

# Debian
icinga2_deb_repos:
  - {
      repo: "deb https://packages.icinga.com/{{ ansible_distribution|lower }} icinga-{{ ansible_distribution_release }} main",
    }
  - {
      repo: "deb-src https://packages.icinga.com/{{ ansible_distribution|lower }} icinga-{{ ansible_distribution_release }} main",
    }

icinga2_pkg:
  - icinga2
  - nagios-plugins

# Redhat
epel_repo_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
epel_repo_gpg_key_url: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
epel_repofile_path: "/etc/yum.repos.d/epel.repo"

icinga2_use_public_yum_repo: True
icinga2_url_yum: "https://packages.icinga.com/epel/ICINGA-release.repo"
icinga2_url_yum_fedora: "https://packages.icinga.com/fedora/ICINGA-release.repo"
icinga2_repo_yum: "/etc/yum.repos.d/ICINGA-release.repo"

icinga2_yum:
  - icinga2
  - icinga2-selinux
  - nagios-plugins-all