---
- name: Check if EPEL repo is already configured.
  stat: path={{ epel_repofile_path }}
  register: epel_repofile_result

- name: Install EPEL repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  until: "result.rc == 0"
  retries: 5
  delay: 10
  when: not epel_repofile_result.stat.exists

- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: not epel_repofile_result.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"

- name: Get Public Yum Repo
  block:
    - name: Get Icinga2 Yum Key on RedHat OS family
      rpm_key: key={{ icinga2_key }}
        state=present

    - name: Get Icinga2 Yum Repo on RedHat OS family (Fedora)
      get_url: url='{{ icinga2_url_yum_fedora }}'
        dest={{ icinga2_repo_yum }}
      when: ansible_distribution == 'Fedora'

    - name: Get Icinga2 Yum Repo on RedHat OS family
      get_url: url='{{ icinga2_url_yum }}'
        dest={{ icinga2_repo_yum }}
  when: icinga2_use_public_yum_repo

- name: Install Icinga2 on RedHat OS family
  yum: name='{{ icinga2_yum }}'
    state=latest
  when: ansible_pkg_mgr == "yum"

- name: Install Icinga2 on RedHat OS family (Fedora > 22)
  dnf: name='{{ icinga2_yum }}'
    state=latest
  when: ansible_pkg_mgr == "dnf"
